-- CreateTable
CREATE TABLE "acta_compliance" (
    "id" TEXT NOT NULL,
    "actaId" TEXT NOT NULL,
    "correo_electronico" TEXT,
    "rif_organo_entidad" TEXT,
    "nombre_completo_revisor" TEXT,
    "denominacion_cargo" TEXT,
    "nombre_organo_entidad" TEXT,
    "nombre_unidad_revisora" TEXT,
    "fecha_revision" TIMESTAMP(3),
    "codigo_documento_revisado" TEXT,
    "q1_acta_contiene_lugar_suscripcion" BOOLEAN,
    "q2_acta_contiene_fecha_suscripcion" BOOLEAN,
    "q3_acta_identifica_organo_entregado" BOOLEAN,
    "q4_acta_identifica_servidor_entrega" BOOLEAN,
    "q5_acta_identifica_servidor_recibe" BOOLEAN,
    "q6_acta_describe_motivo_entrega" BOOLEAN,
    "q7_acta_describe_fundamento_legal" BOOLEAN,
    "q8_acta_contiene_relacion_anexos_normas" BOOLEAN,
    "q9_acta_expresa_integracion_anexos" BOOLEAN,
    "q10_acta_suscrita_por_quien_entrega" BOOLEAN,
    "q11_acta_suscrita_por_quien_recibe" BOOLEAN,
    "q12_anexa_informacion_adicional" BOOLEAN,
    "q13_anexos_con_fecha_corte_al_cese" BOOLEAN,
    "q14_acta_deja_constancia_inexistencia_info" BOOLEAN,
    "q15_acta_especifica_errores_omisiones" BOOLEAN,
    "q16_acta_elaborada_original_y_3_copias" BOOLEAN,
    "q17_incluye_autorizacion_certificar_copias" BOOLEAN,
    "q18_original_archivado_despacho_autoridad" BOOLEAN,
    "q19_copia_certificada_entregada_a_servidor_recibe" BOOLEAN,
    "q20_copia_certificada_entregada_a_servidor_entrega" BOOLEAN,
    "q21_copia_entregada_auditoria_interna_en_plazo" BOOLEAN,
    "q22_anexo_estado_cuentas_general" BOOLEAN,
    "q23_anexo_situacion_presupuestaria_detallada" BOOLEAN,
    "q24_anexo_gastos_comprometidos_no_causados" BOOLEAN,
    "q25_anexo_gastos_causados_no_pagados" BOOLEAN,
    "q26_anexo_estado_presupuestario_por_partidas" BOOLEAN,
    "q27_anexo_estado_presupuestario_por_cuentas" BOOLEAN,
    "q28_anexo_estados_financieros" BOOLEAN,
    "q29_anexo_balance_comprobacion_y_notas" BOOLEAN,
    "q30_anexo_estado_situacion_financiera_y_notas" BOOLEAN,
    "q31_anexo_estado_rendimiento_financiero_y_notas" BOOLEAN,
    "q32_anexo_estado_movimiento_patrimonio_y_notas" BOOLEAN,
    "q33_anexo_relacion_cuentas_por_cobrar" BOOLEAN,
    "q34_anexo_relacion_cuentas_por_pagar" BOOLEAN,
    "q35_anexo_relacion_fondos_terceros" BOOLEAN,
    "q36_anexo_situacion_fondos_anticipo" BOOLEAN,
    "q37_anexo_situacion_caja_chica" BOOLEAN,
    "q38_anexo_acta_arqueo_caja_chica" BOOLEAN,
    "q39_anexo_listado_registro_proveedores" BOOLEAN,
    "q40_anexo_reporte_libros_contables" BOOLEAN,
    "q41_anexo_reporte_cuentas_bancarias" BOOLEAN,
    "q42_anexo_reporte_conciliaciones_bancarias" BOOLEAN,
    "q43_anexo_reporte_retenciones_pendientes" BOOLEAN,
    "q44_anexo_reporte_contrataciones_publicas" BOOLEAN,
    "q45_anexo_reporte_fideicomiso_prestaciones" BOOLEAN,
    "q46_anexo_reporte_bonos_vacacionales" BOOLEAN,
    "q47_anexo_mencion_numero_cargos_rrhh" BOOLEAN,
    "q48_incluye_cuadro_resumen_cargos" BOOLEAN,
    "q49_cuadro_resumen_cargos_validado_rrhh" BOOLEAN,
    "q50_anexo_reporte_nominas" BOOLEAN,
    "q51_anexo_inventario_bienes" BOOLEAN,
    "q52_inventario_bienes_fecha_entrega" BOOLEAN,
    "q53_inventario_bienes_comprobado_fisicamente" BOOLEAN,
    "q54_verificada_existencia_bienes_inventario" BOOLEAN,
    "q55_verificada_condicion_bienes_inventario" BOOLEAN,
    "q56_inventario_indica_responsable_patrimonial" BOOLEAN,
    "q57_inventario_indica_responsable_uso" BOOLEAN,
    "q58_inventario_indica_fecha_verificacion" BOOLEAN,
    "q59_inventario_indica_numero_acta_verificacion" BOOLEAN,
    "q60_inventario_indica_numero_registro_bien" BOOLEAN,
    "q61_inventario_indica_codigo_bien" BOOLEAN,
    "q62_inventario_indica_descripcion_bien" BOOLEAN,
    "q63_inventario_indica_marca_bien" BOOLEAN,
    "q64_inventario_indica_modelo_bien" BOOLEAN,
    "q65_inventario_indica_serial_bien" BOOLEAN,
    "q66_inventario_indica_estado_conservacion_bien" BOOLEAN,
    "q67_inventario_indica_ubicacion_bien" BOOLEAN,
    "q68_inventario_indica_valor_mercado_bien" BOOLEAN,
    "q69_anexo_ejecucion_poa" BOOLEAN,
    "q70_incluye_ejecucion_poa_fecha_entrega" BOOLEAN,
    "q71_incluye_causas_incumplimiento_metas_poa" BOOLEAN,
    "q72_incluye_plan_operativo_anual" BOOLEAN,
    "q73_anexo_indice_general_archivo" BOOLEAN,
    "q74_archivo_indica_clasificacion" BOOLEAN,
    "q75_archivo_indica_ubicacion_fisica" BOOLEAN,
    "q76_incluye_relacion_montos_fondos_asignados" BOOLEAN,
    "q77_incluye_saldo_efectivo_fondos" BOOLEAN,
    "q78_incluye_relacion_bienes_asignados" BOOLEAN,
    "q79_incluye_relacion_bienes_unidad_bienes" BOOLEAN,
    "q80_incluye_estados_bancarios_conciliados" BOOLEAN,
    "q81_incluye_lista_comprobantes_gastos" BOOLEAN,
    "q82_incluye_cheques_pendientes_cobro" BOOLEAN,
    "q83_incluye_reporte_transferencias_bancarias" BOOLEAN,
    "q84_anexo_caucion_funcionario_admin" BOOLEAN,
    "q85_incluye_cuadro_liquidado_recaudado" BOOLEAN,
    "q86_incluye_relacion_expedientes_investigacion" BOOLEAN,
    "q87_incluye_situacion_tesoro_nacional" BOOLEAN,
    "q88_incluye_ejecucion_presupuesto_nacional" BOOLEAN,
    "q89_incluye_monto_deuda_publica_nacional" BOOLEAN,
    "q90_incluye_situacion_cuentas_nacion" BOOLEAN,
    "q91_incluye_situacion_tesoro_estadal" BOOLEAN,
    "q92_incluye_ejecucion_presupuesto_estadal" BOOLEAN,
    "q93_incluye_situacion_cuentas_estadal" BOOLEAN,
    "q94_incluye_situacion_tesoro_municipal" BOOLEAN,
    "q95_incluye_ejecucion_presupuesto_municipal" BOOLEAN,
    "q96_incluye_situacion_cuentas_municipal" BOOLEAN,
    "q97_incluye_inventario_terrenos_municipales" BOOLEAN,
    "q98_incluye_relacion_ingresos_venta_terrenos" BOOLEAN,
    "puntaje_calculado" DOUBLE PRECISION,
    "resumen_cumplimiento" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "acta_compliance_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "acta_compliance_actaId_key" ON "acta_compliance"("actaId");

-- AddForeignKey
ALTER TABLE "acta_compliance" ADD CONSTRAINT "acta_compliance_actaId_fkey" FOREIGN KEY ("actaId") REFERENCES "Acta"("id") ON DELETE CASCADE ON UPDATE CASCADE;
